/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGGER_H_RPCGEN
#define _LOGGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STR_LEN 256

struct log_data {
	char *username;
	char *operation_details;
	char *timestamp_str;
};
typedef struct log_data log_data;

#define LOGGER_PROG 0x20000001
#define LOGGER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERATION 1
extern  void * log_operation_1(log_data *, CLIENT *);
extern  void * log_operation_1_svc(log_data *, struct svc_req *);
extern int logger_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERATION 1
extern  void * log_operation_1();
extern  void * log_operation_1_svc();
extern int logger_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_data (XDR *, log_data*);

#else /* K&R C */
extern bool_t xdr_log_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGGER_H_RPCGEN */
