/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logger.h"

bool_t
xdr_log_data (XDR *xdrs, log_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, MAX_STR_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation_details, MAX_STR_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp_str, MAX_STR_LEN))
		 return FALSE;
	return TRUE;
}
